// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0HidFomTTPpwcx1_LWidsUuboWwugL1E',
    appId: '1:1063004541125:web:06c1ad6e5fee3f6b97a0ac',
    messagingSenderId: '1063004541125',
    projectId: 'billwise499',
    authDomain: 'billwise499.firebaseapp.com',
    storageBucket: 'billwise499.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIFOEThLa6lVEDZ_Pbu3pFvULtsMyaynM',
    appId: '1:1063004541125:android:7b3d20fd615d73c397a0ac',
    messagingSenderId: '1063004541125',
    projectId: 'billwise499',
    storageBucket: 'billwise499.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADehokAhyjj0zvcbVVSxTUs5-BNv69Qu8',
    appId: '1:1063004541125:ios:ea7d62d5f4f415d397a0ac',
    messagingSenderId: '1063004541125',
    projectId: 'billwise499',
    storageBucket: 'billwise499.firebasestorage.app',
    iosBundleId: 'com.example.billwise499',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADehokAhyjj0zvcbVVSxTUs5-BNv69Qu8',
    appId: '1:1063004541125:ios:ea7d62d5f4f415d397a0ac',
    messagingSenderId: '1063004541125',
    projectId: 'billwise499',
    storageBucket: 'billwise499.firebasestorage.app',
    iosBundleId: 'com.example.billwise499',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0HidFomTTPpwcx1_LWidsUuboWwugL1E',
    appId: '1:1063004541125:web:141e731aa68ed5e897a0ac',
    messagingSenderId: '1063004541125',
    projectId: 'billwise499',
    authDomain: 'billwise499.firebaseapp.com',
    storageBucket: 'billwise499.firebasestorage.app',
  );
}
